# This is a basic workflow to help you get started with Actions

name: GeoNode Client CI (tests)

# Controls when the workflow will run
on:
  # Triggers the workflow pull request events but only for the master branch
  pull_request:
    branches: [ master ]
    paths: "./geonode_mapstore_client/client/**"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-front-end:
    if: ${{ false }}  # disable for now
    env:
      working-directory: ./geonode_mapstore_client/client
    runs-on: ubuntu-latest
    steps:
      - name: "Checking out"
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive

      - name: "Setting up npm"
        uses: actions/setup-node@v2
        with:
            node-version: '12.x'

      ############
      # CACHING
      ##########
      - name: "Cache node modules"
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: ~/.npm # npm cache files are stored in `~/.npm` on Linux/macOS
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      ###############
      # NPM CHECKS
      #############
      - name: "Run npm install"
        run: npm install
        working-directory: ${{env.working-directory}}

      - name: "Run ESlint"
        run: npm run lint
        working-directory: ${{env.working-directory}}

      - name: "Run Unit Tests"
        run: npm test
        working-directory: ${{env.working-directory}}
 
